name: Build and test

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check
    - name: Clippy (pedantic)
      # This might be very aggressive and possibly with false positive, but that's the point
      run: cargo clippy -- -D clippy::pedantic
    - name: Build
      run: cargo build --verbose
    - name: Build doc
      run: cargo test --verbose
    - name: Run tests
      run: cargo test --verbose
